package by.htp.ex.controller;

public enum CommandName {
	GO_TO_BASE_PAGE, GO_TO_LOGINATION_PAGE, GO_TO_REGISTRATION_PAGE, GO_TO_NEWS_LIST, GO_TO_VIEW_NEWS, DO_REGISTRATION,
	GO_TO_ADD_NEWS, GO_TO_EDIT_NEWS, CHANGE_LOCAL, DELETE_NEWS, EDIT_NEWS, ADD_NEWS, GO_TO_ERROR_PAGE,

	DO_SIGN_IN, DO_SIGN_OUT
}
